### PR TITLE
Some UI Changes

### PR DESCRIPTION
**Pull request by RodrigoCard**
I created a new branch with some UI changes:

* removed the about popover
* included an about tab so we can have more space to put the proper credits

---

I was about to create a new tab to include **Disable** and **Uninstall** buttons, and other misc options but I am not sure how it should look like, So I created this pull request to discuss these ui changes.

*The important question is:*
**Any thoughts about how these new UI elements should look like?**

My random thoughts:
* a new "Advanced" tab with this kind of stuff
* squeeze these options in the about menu.
* rename the deadzone menu to "Advanced" and cram that there too.

### CODE REVIEW

**Comment by RodrigoCard** [comment]
Pics of the changes so you can save time :)

pic1
pic2

**Comment by MaddTheSane** [comment]
I'm thinking that any uninstall button should launch a separate app, quit System Preferences, then uninstall the driver.

**Comment by Shimunogora** [comment]
I love the update, but I think a big UI improvement would be to change the title of the application to say "Xbox" instead of "XBox," unless there is a specific reason for this. In the preferences pane it's stylistically correct as "Xbox 360 Controllers," but does anyone else think it is a bit of an eye sore?

**Comment by FranticRain** [comment]
Personally, I'm of the opinion that any uninstall should just be a .command file shipped with the driver DMG. I don't believe scripts can uninstall themselves, so a separate file would allow users to have a clean uninstall without leaving some file around somewhere. As for a disable and re-enable feature, can we run applescript from within the program? If we can, then we can just use my scripts. If not, it might be easy to just have the program run the shell scripts from a button within the preference pane.

**Comment by slime73** [comment]
> I think a big UI improvement would be to change the title of the application

This is slightly off-topic, but now that the Xbox original and Xbone controllers are supported I think it'd make even more sense for the prefpane title to be "Xbox Controllers" rather than "XBox 360 Controllers".

**Comment by bleeq** [comment]
@Shimunogora Yeah, that's bothered me for awhile, so I've gone ahead and changed all the string & text references of XBox to Xbox: cc092d85d1fabfb00bce0619e7d78ec218ecbc11

**Comment by RodrigoCard** [comment]
@FranticRain @MaddTheSane I am pretty sure I saw an Uninstall button in some third party preference panes, I will see if it is possible to run an uninstall script from the prefpane that doenst left anything behind. I think It is better to be able to uninstall without having the DMG file, because I generally delete these files right after installing stuff and I believe lots of people do that.

@FranticRain If you cant run Applescript from the prefpane (which I doubt) you probably can run a shell command. I will check that.

@Shimunogora @bleeq I never noticed that! :O at last I wrote the "Xbox" in the temp text correctly hehe.
@bleeq please make a pull request with your changes :)

@slime73 Agreed! This is something I was thinking about for some time... Maybe we should call it "Xbox controllers for OS X" or something similar that helps Google indexing.

**Comment by RodrigoCard** [comment]
And.... Where do you think we should put these kind of buttons? :P

I am inclined to create an "Advanced" tab and include them and the deadzones together...

**Comment by FranticRain** [comment]
The Applescript portion was just to make sure we had superuser privileges on the script. [Shouldn't be too hard to do.](https://stackoverflow.com/questions/4909702/run-applescript-from-cocoa-application) And yes, absolutely merge all of that into an advanced tab.

**Comment by gustaflindqvist** [comment]
Really like the changes to the GUI. Rename the "deadzone" menu to "Advanced".

**Comment by RodrigoCard** [comment]
What you think?
advancedtab

**Comment by MaddTheSane** [comment]
Looks good to me.

**Comment by FranticRain** [comment]
Since we have so much space to describe the enable function, we might add something like: "This may be useful when using OnLive or playing a game ported by Aspyr."

**Comment by RodrigoCard** [comment]
Done!

Could someone help to fix clip view issues? If I reposition and recalculate the constraints, it breaks another constraint...
and nothing seems to make the contents of the second tab go 1 pixel up while keeping Interface Builder happy :-/

**Comment by MaddTheSane** [comment]
I can do it.

**Comment by MaddTheSane** [comment]
Ah yes, the Clip View. This seems to be an ever-present bug in Xcode. It just blurts out the warning, but it doesn't affect the compiled nib. To my knowledge, it can be safely ignored.

**Comment by FranticRain** [comment]
Slightly unrelated, but is it possible to save collections of settings as a struct? I'd like to add some sort of rebinding presets as per request, but I don't want to massively overload the save/load functions.

**Comment by MaddTheSane** [comment]
The closest thing to a struct you can store would be an NSDictionary (or CFDictionaryRef) with only some classes.

**Comment by RodrigoCard** [comment]
Well, everything is ok with this one now, I will include the button's functionality, write proper credits and merge soon.

That said, I think we should do a release after, there are already so much nice stuff pending. :)
more nice stuff can come later.

**Comment by FranticRain** [comment]
Unless we see any immediate need for axes mapping or mapping presets in general, its good to go on my end.

**Comment by RodrigoCard** [comment]
Enable and Disable driver working.

The prefpane still needs to check if the driver is enabled and uncheck the Enabled checkbox properly. A simple kextstat wont work because the kext will be loaded if a controller is connected for the first time.

it still doesn't prevent the driver from loading if the checkbox is disabled, it just disables if it is
enabled.

How it should be done? the kext should read a configuration file? the daemon? will #67 be a problem again?

Any thoughts?

**Comment by RodrigoCard** [comment]
Also, good news, I was able to remove the prefpane from the prefpane itself, if I run the apple script inline (no external script files).
So, I will just write a proper uninstall script and embed it :)

**Comment by FranticRain** [comment]
It seems like the best we can do is check the box by default, and force users to use the prefpane to disable it when a controller is connected. So basically gray it out in checked format until a controller is connected.
There may be a better way to do this, but this is the one that pops into my head.

**Comment by RodrigoCard** [comment]
Sorry, I've been busy lately, I will update this soon.

**Comment by Contez** [comment]
Just my opnion: while the mockups are quite nice I agree I must say I don't think the proposes Advanced tab is conceptually correct.
What I mean is that there a bunch of system-related (uninstall/disable driver) and control related (deadzones) settings together.
If you look at the panel the overall setting (which conceptually should refers to all the settings below) is the dropdown menu selecting which controller, which is ok for deadzones (as they are controller specific), but not for disable and uninstall controls.

Frankly I would go for the Uninstall button in the About page (as other prefpanes do too) and the Enable checkbox in the current tab (Advanced), but clearly separated (maybe before them) from the controllers stuff block.

Anyway just my two cents, good job so far and happy to be here! ;)

Ric

**Comment by RodrigoCard** [comment]
Thanks for the opinion @Contez , I will make some changes.

**Comment by Contez** [comment]
You're more than welcome, glad to be of any help. ;)

**Comment by RodrigoCard** [comment]
Sorry for taking too long. I will do some testing for uninstall/enable/disable cases and tell you if I think it is ok to merge.

---
About the Uninstall button, I will leave where it is for now. And move it to about when we need more space for additional options.

**Comment by RodrigoCard** [comment]
People, is there a way to check if the Daemon is running?

I can check the return of
```
sudo launchctl list | grep com.mice.360Daemon
```
is there a cleaner way?

**Comment by RodrigoCard** [comment]
I think it is OK to merge now, it is doing everything it should do (with current limitations).

The only known issue is that if you disable the driver and completely close the System prefences, the check box will appear enabled and you need to click it twice to enable it again.

Any feedback before merging? Thanks! :)

**Pull request merged**
