### PR TITLE
Add rumble disable

### LINKED ISSUE #92: Help with deactivating vibrations
Hey there,
I was searching for updated versions and was lucky enough to land here.

I use a wired XB360 controller and play almost only CS:GO (I know, I know... :) ).

Apart from some hickups with the movement with the analog sticks, the only thing really giving me a hard time are the vibrations. I tried it with re-mapping and using different buttons for shooting - still - just doesn't feel right. So I was hoping that someone here can maybe help me out.

I have 0 experience with commands/terminal. Is there a way to deactivate the vibrations without taking the controller apart and without messing up my mac.

Don't want to sound stupid. I really don't have any clue how to change it.

And thank you all for keeping this alive!

### PR DESCRIPTION
**Pull request by FranticRain**
I changed "Xone Rumble Options:" to "Rumble Options:" For non-Xbox One controllers, you are given the options "Default" and "None." If you are using an Xbox One controller, it also gives you "Triggers Only" and "Both." I've been working on my driver, so I can't test it, but all of the code is super straight forward.

Also I snuck in a new Xbox One controller. For some reason, my driver doesn't work with PowerA controllers, but this one might? I'd like to get an installer for this version once it is merged in order to test the additional controller support.

EDIT: Oh yeah, resolves #92

### CODE REVIEW

**Comment by RodrigoCard** [comment]
Oh, great, I will do some testing.
I will merge #82 then this one.

There are a lot of pending fixes and new features done and no release...
Lets get a new version done this week, if possible? :)
I will get some stuff done to make a proper release.

**Comment by FranticRain** [comment]
Anything I need to do? I'm pretty free this weekend.

**Comment by RodrigoCard** [comment]
There is a few stuff here in this list https://github.com/d235j/360Controller/milestones/0.15%20version
I will add the pending devices right now, so disregard the "new devices" issues.
#54 and #21 is fixed by #82 (kind of, #66 is blocking the proper uninstallation/disabling, but it works most of the time)

So it leaves #80 and #67 to be investigated.

Does this pull request fixes #80?

**Comment by FranticRain** [comment]
No, but I have an idea where the problem may be. I'll look into it.

**Comment by FranticRain** [comment]
The FFEffectStart call returns a 0 HRESULT. So I don't know what the problem is.

**Comment by RodrigoCard** [comment]
@FranticRain sorry for not checking the pull request before.
I tested it and it is working well, except that the Xbox One rumble list is not showing its exclusive options
xonerumble

**Comment by FranticRain** [comment]
It would show up if the settings synced properly. Its checking to see if the controller type is Xbox One, but since all of the settings are void, it can't ever show them.

**Comment by RodrigoCard** [comment]
Well... I thought about letting all the options available and if it is not valid (for 360 controllers) fall back to "default"... but, it is ugly.

I will just merge this, clean up some stuff, write the new credits/readme/etc and release a beta,

**Comment by RodrigoCard** [comment]
we can try to fix the settings saving bug after that.

**Pull request merged**
