### PR TITLE
Linear Scaling Deadzone Option

### PR DESCRIPTION
**Pull request by FranticRain**
Provides a potential fix for #58 by allowing a linear acceleration based on the deadzone.
linear_deadzone

### CODE REVIEW

**Comment by FranticRain** [comment]
Color isn't great, but should get the point across.

mario_deadzone

**Comment by blakekl** [comment]
Sweet! Looks like it works pretty good, although looks like you're still sending values from within the controller's deadzone. Is that intentional or am I misunderstanding the red lines?

**Comment by FranticRain** [comment]
Basically its taking the range: (deadzone to max stick value) and scaling it to the range (0 to max stick value) at the driver level. So it is hard to represent at the preference pane level. What you see on the preference pane currently is the value all games see, not the raw value the controller is sending. So it looks like you are violating the deadzone, but you can tell when using it that its just scaling.

I could potentially reverse the math of the preference pane side and create a less opaque dot to represent the actual position of the joystick. I'm not sure if its needed or not.

**Comment by blakekl** [comment]
Oh okay. It's probably not necessary for a separate opaque valu representing actual output. I can see that being useful if we went with a full blown Bézier curve, but for this application I think it works fine.

My only concern now is if anyone understands what the linear checkbox means. I'm sure it will be documented, but having an intuitive interface would be ideal. Not sure we can do anything without taking up a bunch more space. Maybe calling it deadzone scaling instead of just linear? I don't know.

**Comment by blakekl** [comment]
Maybe 'preserve full output values'? It's still a huge string compared to linear though.

**Comment by FranticRain** [comment]
Yeah, I struggled with the naming as well. So I just decided to name it linear in hopes of someone coming up with a better name.

**Comment by HeinAtCERN** [comment]
Hi there,

I think this should be default behavior, no checkbox needed. Why should you want to have the values simply cut off at the deadzone?

Awesome work, btw, Ilaikit!

**Comment by RodrigoCard** [comment]
@HeinAtCERN 
Because this is the way that the driver worked since forever and some games may assume this behavior because of that.

**Comment by HeinAtCERN** [comment]
Hmm, I don't agree, sorry. 
(1) Your "since forever" argument would only make another argument stronger, but it doesn't stand for itself. Would you maintain something irrelevant only because it has been there forever?
(2) What exactly does a game assume about this behavior? Does a game sense that there is a sudden turn-on in values and correct for it, e.g. make the transition smoother? I don't think so. I would agree, though, that it could be a slightly different experience if you as a gamer are used to large deadzones. 
But this I wouldn't consider standard, because the deadzone feature ultimately takes away from the playing experience, by throwing away parameter space (despite of correcting it) in order to account for hardware inaccuracy.
Cheers! =)

**Comment by RodrigoCard** [comment]
Feel free to disagree :)
Sorry for not explaining better.

My argument about "since forever" is from a developer perspective of "dont break anything that is already working".
Lots of games assume some arbitrary deadzone to prevent unwanted input, if you scale the value, the game will have an even higher deadzone.

And I agree with you, Zero is zero, and the game developer shouldnt be bothered to take messy dead zones into consideration, unfortunately this is not how stuff works.

Anyway, this is a great option, but I still think that it shouldnt be enabled by default unless you can test all games :)

**Comment by blakekl** [comment]
@HeinAtCERN I agree with Rodrigo. There's no reason to change the default behavior. At this point I think the name is the only concern. So far, I've come up with the following; I'm not particularly happy with any of them... just throwing ideas at the wall at this point.

Maintain Axis Range
Deadzone Scale Compensation
Deadzone Scaling
Preserve Output Range
Deadzone Recalibration
Deadzone Smoothing

Deadzone smoothing is probably my favorite. I think users could guess the functionality from that name.

**Comment by RodrigoCard** [comment]
@blakekl @FranticRain 
There is a word for that kind of scaling used in Mathematics/Statitics: "[Normalization](http://en.wikipedia.org/wiki/Normalization_%28statistics%29)"
Which means exactly what you want.

So I would write something like:
* Normalize Axes
* Normalize Range
* Normalize Output

Or simply:
* Normalize

**Comment by FranticRain** [comment]
Normalize sounds great. People should be able to figure it out, and if not, hopefully they will check the docs or at least try it out and figure it out.

**Comment by blakekl** [comment]
Perfect. Normalize works. I knew someone would find the right word.

**Comment by HeinAtCERN** [comment]
Hi. Ok, the arbitrary deadzone of some games and not increasing it further is actually a good argument. =) Thanks! Alright then. I'd call it "Normalize range", but "normalize" is definitely a good word for it. Cheers!

**Comment by RodrigoCard** [comment]
@FranticRain 

I just tested it, and it looks like it is working well, tested with Super Mario 64. :)
Nice job!

###About the UI:

**1-** About the deadzone panel, I really think the user should see the real output in the stick areas (and the controller test too, btw), more or less like the old behavior, where the point dont move at all when inside the deadzone, but with the normalized output if enabled.

**2-** complementary Idea: Maybe we should include another lighter colored dot to show the input, so we can see the difference between the input and output, this one would show exactly what the current one is showing.

I think **1** should be enough to let the user figure it out alone, and **2** will make him/her understand that for sure.

###Also
```
clang: error: no such file or directory: '/Downloads/360Controller-0.14-unofficial/Pref360Control/MyAnalogStick.m'
clang: error: no input files
```
Your xcode project is still pointing to the wrong location,
just saying :)

**Comment by FranticRain** [comment]
I should be able to implement 2 no problem. As for the xcode thing, I don't even understand how that is happening. I don't upload my xcode settings. :\

I'll remove it and re-add it. Stupid hunk of junk.

**Comment by FranticRain** [comment]
Oh I see. I've been using the .xcworkspace and it didn't propagate the changes back to the .xcodeproj. Now I've switched back to the .xcodeproj and everything should be fantastic. Will upload some .gifs of my progress in a little bit.

**Comment by FranticRain** [comment]
So the design on the main tab doesn't look great. I'm not sure how to clean it up. Maybe someone will have a better idea than me.
nice_deadzone_preview

But I'm pretty happy with how this one turned out.
spartan_deadzone_preview

**Comment by RodrigoCard** [comment]
Looks great.
I think the main tab should show just the final output, this ghost thumb stick May confuse the users, don't you think?

About the dead zone tab. The grey one is the normalized one, right? Looks nice.
I think the movement of this one that should show in the main tab.

What you think?

**Comment by FranticRain** [comment]
In my mind, the black square of ```MyAnalogStick``` was always the value that was being sent to games. They grey square represents the sticks position If the output were not normalized. It makes sense to make that the one that is shown on the main tab though. I'll make the necessary changes and then push it.

**Comment by RodrigoCard** [comment]
I agree with you. I just thought it was the opposite behavior. So no (c) Nate necessary. Sorry about that. =)

**Comment by RodrigoCard** [comment]
Stupid auto correction.
"(C) Nate" should be "change"

**Comment by FranticRain** [comment]
I was working on a port of this driver from IOHIDDevice to IOUSBHIDDriver, and I noticed that the ```OSString* Xbox360ControllerClass::newProductString() const``` in some cases returns ```Xbox Original Wired Controller``` not ```Xbox 360 Wired Controller``` as you would think. Is that a bug or is that expected behavior?

**Comment by RodrigoCard** [comment]
"Xbox Original Wired Controller" should show only for... Xbox Original Wired Controllers and not for 360 controllers :P , if this is not the case, there is a bug.

**Comment by RodrigoCard** [comment]
@FranticRain finally took some time to test today.
It is working almost-wonderfully, but I found something I dont know if it is a bug or a feature:
captura de tela 2015-02-19 as 21 17 27
I checked the inputs received in a SDL application, and I can go further unnormalized than normalized.
This somewhat makes sense to me since analog sticks tend to go out of the imaginary joystick circle (vector length > 1.0) and normalization makes sure the vector length is always <= 1.0.

*It should behave that way, right?*

**Comment by RodrigoCard** [comment]
About the project files:
Is the xcworkspace outside the xcodeproj file really necessary? It still gives some conflicts for me sometimes when testing.

I see that a change you made in the project file breaks forcefeedback for me:

this line is included:
```
EXPORTED_SYMBOLS_FILE = Feedback360/Feedback360.exp;
```
and this one is excluded:
```
UNEXPORTED_SYMBOLS_FILE = Feedback360/Feedback360.exp;
```
What does exactly this does?

**Comment by MaddTheSane** [comment]
`UNEXPORTED_SYMBOLS_FILE` lists the symbols that will explicitly *not* be exported. `EXPORTED_SYMBOLS_FILE` lists the symbols that will *only* be exported.

I did open a pull request to @FranticRain's repo that will fix the symbol issue.

**Comment by FranticRain** [comment]
@RodrigoCard Yeah, its performing as intended. There might be a way to make it more accurate, but I want to keep the math simple so we don't introduce any sort of crazy latency with a bunch of processes every time we get a packet. So really, its a bug, but we can put it in the users manual, so now its a feature! Its just fine either way.

**Comment by RodrigoCard** [comment]
There are no issues for me, looks okay to merge. :)

**Pull request merged**
