### PR TITLE
New pref360 control

### PR DESCRIPTION
**Pull request by Pyroh**
I've just updated prefpane's UI. Just take a look :
screen shot 2015-01-22 at 11 11 55
It's fully working and can be added to master if you want.

But here are some improvement I could make : 
- When I designed the controller's view I made it able to light the LEDs around the home button. I don't know how to get this information in code.
- I can design a controller's view to depict an Xbox One controller depending on what type of controller is connected/viewed.
- I think we can get rid of the *about* box, put the *right stick* box under the *left stick* box and gain more room for the controller's view. 
- As you can see I just own a FightStick and there's still things untested like RT and LB levels and the new battery monitor.

### CODE REVIEW

**Comment by MaddTheSane** [comment]
This looks super-promising. I'll take a look at before merging.

**Comment by Deph0** [comment]
Any chances we can keep shoulder-button rumble ui and maybe sticks+dpad animation? screenshot looks supercool

**Comment by RodrigoCard** [comment]
Looks Very good!
Fun fact: I was just thinking that the pref pane needed a redesign and Bam! Got your emails :)

I agree with the improvements you mentioned.
I think that the about box needs to be changed or dumped, maybe a bigger about tab or something.
That would also help to make space to include more features like #58 #47 #23 #21 in the future.

**Maybe we even should change the project's Name!**
Now that it is a multi-generation-forked Xbox controller driver without original author's support.

I will share more of my thoughts later when I see that in motion.

**Comment by MaddTheSane** [comment]
Removing the about box wouldn't affect #47, as the person wanted it in the menu bar at the top of the screen.

Still, I agree that the about box could be shunted to another tab, or even removed entirely.

**Comment by Pyroh** [comment]
I'm happy you like it !
I'll do some extra code modernisation. Since the target is 10.9+ is Swift code OK ? 
I'll look forward to add some controllers artwork such as the X1 one.

Any hint on how to get the viewed controller's number ?

**Comment by MaddTheSane** [comment]
Hopefully, in the future, 10.7 support will be re-done, but that will mean setting up a previous version of Xcode and stuff. I have some preliminary work on one of my branches.

So I'd hold back on adding Swift code right now.

**Comment by Pyroh** [comment]
As soon as LLVM doesn't drop below v4.0 it's ok for me. 
No swift for now.

**Comment by FranticRain** [comment]
Do we want alternate versions of this depending on the controller? I've got some free time this weekend and probably could make some graphics for the Xbox One controller and OG Xbox controller. Could also consider generic fight stick appearance, but as far as I know, there isn't an easy way to pick out the controller's real identity from the Pref Pane's end. I could be completely wrong, haven't spent much time with the code.

**Comment by Pyroh** [comment]
If you can just wait a little I'll put a pull request with this kind of thing :
screen shot 2015-01-24 at 12 04 33
But if you want to draw more controllers (I was going to do it to) let me know and remember that the view in which they are going to be drawn sizes 465x330. 
It would be a good thing if we would juste have to tell the view which controller to draw instead of swapping views.
In the next commit I'll add the PaintCode's file with the artworks.

**Comment by FranticRain** [comment]
If you wanted to do it, I definitely won't tread on your toes. I just sort of hang around here and make sure that the driver makes sense for non-360 controllers. It looks fantastic, keep up the good work.

**Comment by FranticRain** [comment]
As for telling the view which controller to draw, it might actually be a good idea to add a new value to the settings packet that is passed between the driver and the preference pane. Ex Pref360ControlPref's changeSetting and _60Controller's readSettings. You could pass the controllerType variable from the driver to the preference pane. That would solve which series of control it was, but it wouldn't discover such idiosyncrasies such as being a fight stick or not. The main solution for that would probably be to use DeviceItem's GetDeviceName and then check if the string returned contains "Fight" or "Stick." Hope that helps!

**Comment by RodrigoCard** [comment]
I just built the prefpane and tested it, Looks really good in motion!

Some thoughts and findings:
* the left stick stretches and squishes a bit when moving, the right one looks perfect
* while the new layout looks much better, you cant see the controller's sticks values properly, if it is correctly centred or not, unlike the older layout. Which shouldn't be a a real problem unless...
* ... you want to adjust the deadzone sliders, in which case, precisely visualizing the stick values helps a lot. Thoughts?
* still about the deadzone... the "linked" Deadzone is not really a circle, or is it?

**Comment by Pyroh** [comment]
- I fixed the left stick behaviour.
- We could show sticks' values but I don't think it's needed. 
- I think that since stick motion is actually circular, the linked deadzone is also circular. At least it made sense to me... (non linked deadzone should be portion of squares. But it's a lot of work I didn't do...)

What will come next (as soon as you answered, actually) is a bigger controller's view and a popover instead of the about box. What do we write in that popover ? Do we keep the old about text ?

**Comment by FranticRain** [comment]
We could consider this a user friendly view, and have an alternate "tweaker" menu, maybe on a different tab, that showed raw values and inputs in a more technical way. That could be immensely useful to someone with a drifting stick or some other weird technical issue. Other ideas I had for such a menu would include user-facing bit swapping of button packets. So if I user had a controller that for some crazy reason the b button worked like an a button, they could swap the bits in their packet. If thats something we decide we want, I can probably slap it all together if no one else wants to.

**Comment by RodrigoCard** [comment]
@Pyroh Dont worry about that, also, the bigger version looks better and seems to alleviate the issue. :)
"About the About": That text needs to be changed anyway. Just put a place holder in a big box and I will write the proper credits with all the contributors later. :)

@FranticRain I think it is a very good idea.

**Comment by Duros** [comment]
Wow, this is a very big improvement! It looks very nice.
But why not take the first design, hide the "about" in a tab and put the 2 analog stick boxes underneath for deadzone improvement. And you still have room for more check boxes for new features.

**Comment by blakekl** [comment]
@FranticRain 
This also makes sense where we could add the curve editing options for #58

**Comment by FranticRain** [comment]
@blakekl Great idea. I'll look into that.

**Pull request merged**
