### PR TITLE
Support for Xbox original controller

### PR DESCRIPTION
**Pull request by kasbert**
The driver detects Xbox original automatically and converts received reports to Xbox 360 format. It fakes the USB identifiers, so it shows to applications as a 360 wired controller.

Tested with a Chinese clone controller and Lego the Movie Videogame.

Maybe report fiddling could be moved to the Controller class like in the wireless driver.

### CODE REVIEW

**Comment by FranticRain** [comment]
If it makes any difference, I think you should merge this one first. My implementation is sloppy and I could clean it up based off of this implementation.

**Comment by MaddTheSane** [comment]
It'd be fine with me if we merged this one first.

**Comment by kasbert** [comment]
@RodrigoCard I can help testing the driver. The controller is currently in active use.

**Comment by RodrigoCard** [comment]
Just a quick question, did someone test the driver with a genuine Xbox Original controller (both models)?
Is the product/vendor IDs the same?

**Comment by MaddTheSane** [comment]
I have a knock-off controller that works fine with the new version.

**Pull request merged**
