### PR TITLE
Add basic Xbox One controller support

### PR DESCRIPTION
**Pull request by FranticRain**
Input from the Xbox One controller is converted into 360 controller format. No rumble implemented.

I suggest that this be tested thoroughly before being added. I don’t have a wired 360 controller to test with, so I don’t know how it might impact other controllers.

### CODE REVIEW

**Comment by MaddTheSane** [comment]
The feedback is handled by the `Feedback360` plug-in. The `setReport` function seems to only send a few bytes to set the rumble status.

**Comment by FranticRain** [comment]
I've got some basic support for rumble, however I don't think that the plugin is sending me enough data. As far as I can tell, I receive type, length of packet, big, little. It doesn't provide any sort of accommodation for how long to rumble or if the force feedback is continuous or a single rumble effect. If you want to see more of what I mean [this should explain the rumble packet for the Xbox One controller.](https://github.com/quantus/xbox-one-controller-protocol)

Also, are there any games known to support force feedback so that I can make sure it works in a real situation?

**Comment by MaddTheSane** [comment]
Dust: An Elysian Tail supports force feedback. Also, Fez.

As @d235j did re-write the force feedback driver from the original TattieBogle driver, he may be able to help integrate the force feedback support for the Xbox One controller.

**Comment by RodrigoCard** [comment]
@FranticRain Some emulators like sixtyforce have Forcefeedback support too.

**Comment by MaddTheSane** [comment]
Also, I'm thinking that having the Xbox One driver have its own subclass may make it possible to have a feedback driver for the Xbox One controller in its own subclass.
I'll try to hammer out an example of a possible Force Feedback source tree soon.

**Comment by FranticRain** [comment]
Sounds great. Thanks for the help!

**Comment by MaddTheSane** [comment]
Here's a link to my work: https://github.com/MaddTheSane/360Controller/tree/MultipleFFDrivers
Note that this is forked from the `yosCodeSign` branch.

**Comment by FranticRain** [comment]
I'm bad at git and really messed this up. Will re-create.

**Pull request closed without merging**
