### PR TITLE
Add Mapping, Xbox One Rumble Selection, and Deadzone Detail View

### PR DESCRIPTION
**Pull request by FranticRain**
Okay there is a lot to cover. I spent all weekend putting it together. First and foremost are the known issues:
 - Because of the settings bug #67, the Xbox One rumble options will show up for all controllers, they just only do things for the Xbox One controller.
 - Second, if you hold down a trigger to create any rumble effects, it will not clean itself up upon tab change.
 - Third, the deadzones tab looks a little bit empty. Not really a big deal

### Main Panel

Nothing too crazy here, just added the Popup box that allows the users to change where the rumbles are sent. Tested with the preference pane and Fez.

To keep things from being too confusing, the buttons don't light up on this page when pressed. The image is static until mapping starts, then individual buttons will light up to denote which one needs to be pressed. Should allow for any button to look like any other button. Could potentially be used to fix issues with SDL maybe? It is as of yet untested. The list over to the side tracks the changes in buttons, but of course doesn't load properly due to #67 again.

These provide a more detailed view of the deadzones, and all of the data should sync across changes made in either tab.

### Minor Improvements
 - Fixed some extra log writes from Xbox One controllers
 - Added tab based checking so that the controller doesn't rumble on every tab
 - Added setting to check type of controller. Useful for more complex art.
 - Other minor stuff.

### CODE REVIEW

**Comment by RodrigoCard** [comment]
Great, I will do some testing.

**Comment by Pyroh** [comment]
Nice work !
Anyone has an idea on how to know what kind of controller is connected in order to adapt controller view ? My first though was to add a key in the [Info.plist file](https://github.com/d235j/360Controller/blob/master/360Controller/Info.plist file of the 360driver) (IOKitPersonalities) from 360Driver.
These informations seem to be used by both the daemon and the driver tool but I don't know if we can add key at will or if it must have a strict pattern matching.

**Comment by FranticRain** [comment]
@Pyroh I added an enum that the driver sets to the settings packet. When #67 is fixed, you should be able to simply use that enum. However, for a quick and dirty fix that works now, its best to check the selected index of ```_deviceList``` for the strings ```Xbox One``` or ```Xbox Original``` and then act accordingly.

**Comment by RodrigoCard** [comment]
just a silly thing: looks like you didnt include MyAnalogStick.m correcly
```
clang: error: no such file or directory: '/Downloads/360Controller-0.14-unofficial/Pref360Control/MyAnalogStick.m'
clang: error: no input files
Command /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang failed with exit code 1
```
I deleted and readded both MyAnalogStick.m and MyAnalogStick.h and it worked.

By the way, I am thinking about removing that "Info" button from the bottom right corner of the Controller test tab and put the credit info in another tab, uncluttering that tab.

**Comment by RodrigoCard** [comment]
I tried to commit and pull the build fix to this pull request but apparently I cant do that, heh

**Comment by FranticRain** [comment]
Hah. Is the fix just removing it and then re-adding it? Not sure how I messed that up in the first place.

**Comment by MaddTheSane** [comment]
Just a tiny thing: I'd rename "Reset Remapping" to "Reset Mapping".

**Comment by RodrigoCard** [comment]
I think it is ok to merge.

**Pull request merged**
