### PR TITLE
Add Southpaw & XboxOne2015 Support

### PR DESCRIPTION
**Pull request by FranticRain**
Southpaw swaps the sticks. So the left stick reports the right stick input and the right stick reports the left stick input. This is a new option, "Swap Sticks" on the General tab. This should partially help with #79 but it doesn't mess with the triggers, whatsoever.

### CODE REVIEW

**Comment by d235j** [comment]
Any reason we can't use a property to identify which joysticks have stuff swapped, and automatically handle it?

**Comment by FranticRain** [comment]
I'm not sure what you mean. With only two joysticks, you only have two configurations. Normal and swapped. Unless you're referring to the axes.

**Comment by d235j** [comment]
@FranticRain: If you have one swapped controller and one normal controller, do you need both to be swapped? Or are these settings per-controller?

**Comment by FranticRain** [comment]
@d235j It is supposed to be a per-controller feature. I haven't tested it with multiple controller though.

**Comment by RodrigoCard** [comment]
@FranticRain I changed more stuff on the prefpane, sorry :P
by the way, https://github.com/d235j/360Controller/issues/97#issuecomment-125479634 :)

**Comment by FranticRain** [comment]
There we go, fixed it. Hopefully Tattiebogle will accept the Xbox One changes, because it's really going to stink if he doesn't.

**Comment by FranticRain** [comment]
I finally got a 2015 Xbox One controller. All of the code I wrote into my driver to make it work is perfect, but for some dumb reason it didn't work with my driver. Boy I can't wait for official 0.15 so I can deprecate that piece of garbage. I also added in the fix for #126.

**Comment by tcook1231** [comment]
hey do either of you, @FranticRain  or @RodrigoCard,  mind putting this into a pkg. I am not a developer and would rather not shell out the cash just for one driver. Also I have been a bit of a pain in your guy's ass for the past little bit and I am really sorry about that.

**Comment by RodrigoCard** [comment]
Hi @FranticRain Sorry for the delay.

Would you mind to redo your changes to the preference pane based on the one from the main branch?
apparently, the merge here undid some stuff I changed.

It may look more or less the same but I Mostly changed/deleted/added some autolayout constraints to prevent some recurrent misalignments and avoid that "empty prefpane" that happens sometimes.

Also... (next message)

**Comment by RodrigoCard** [comment]
It worked perfectly with my Xbox One controller, but when I connect a second controller with swap enabled, the swap starts enabled for the second controller too.

That said, I cant confirm the second/third controller works because it does NOT work at all for wireless xbox 360 controllers. Either Individually or with all of them connected.
I dont have a wired xbox 360 controller to test.

**Comment by FranticRain** [comment]
I replaced my entire xib with the raw from the repository, then re-added my "Swap Sticks" checkbox. Hopefully that fixes the problem.

I just tested it again with two Xbox One controllers, and did not experience the same auto-swap. Your experience may just be a fluke.

I realized that remapping doesn't work on Xbox 360 controllers as well. Do wireless 360 controllers not go through the `Xbox360ControllerClass::handleReport` method?

**Comment by FranticRain** [comment]
Okay, I fixed the Wireless 360 Controller stuff. Wireless controllers now remap axes and buttons properly. Additionally, I did notice that sometimes the power off button in the preference pane doesn't have an icon in it, but I don't think that is my fault.

**Comment by RodrigoCard** [comment]
Multiple Wireless controllers working! :)

About the problem I said before, it still happens, but no, it doesnt really swap sticks on newly inserted gamepads, it is just the UI that starts with "swap sticks" enabled, and you need to click twice to enable it properly.

Steps to reproduce:
- Insert Xbox One controller
- click swap sticks
- Insert a new controller (wireless 360 in my case)
- switch to this controller
- the "swap sticks" checkbox for this controller is enabled, but it does nothing
- if you insert the new controller with the previous one's "swap sticks" disabled it doesnt happen

--------
About the Prefpane, there is something wrong yet, but dont worry, I will redo that after the merge in another way, hopefully preventing the displacements for real.

**Comment by FranticRain** [comment]
Whoops. I missed a line in resetDisplay. Its in there now, and the problem should be solved.

**Comment by RodrigoCard** [comment]
All right! :)

**Comment by RodrigoCard** [comment]
I released another beta with these changes :)
The new xbox one controller is something important to support :P

:package: https://github.com/d235j/360Controller/releases/tag/v0.15_beta2_unofficial

**Comment by FranticRain** [comment]
It sure is. I really hope that this was a one time thing and this doesn't happen again with the Elite controller. I super duper don't want to buy one of those. Also I hope that wireless adapter comes out soon.

**Comment by RodrigoCard** [comment]
I am almost pretty sure it will happen again :(

**Pull request merged**
